---
# tasks file for nginx

- name: Install epel-release [CentOS]
  tags: [common, centos]
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS'

- name: Enable amazon-linux-extras for required packages
  shell: "amazon-linux-extras enable {{item}}"
  become: yes
  with_items:
    - nginx1.12
  when: ansible_distribution == 'Amazon'

- name: install components
  yum: name={{item}} state=present
  with_items:
    - nginx
    - git
  tags: [ 'packages' ]

- name: Nginx requires user www-data user to start
  user:
    name: www-data

- name: write our nginx.conf
  action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Create /etc/nginx/sites-enabled and sites-available
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/etc/nginx/sites-enabled"
    - "/etc/nginx/sites-available"


- name: Put in some default sites for troubleshooting
  action: template src=default-site.j2 dest=/etc/nginx/sites-{{item}}/default
  with_items:
    - available
    - enabled
  notify: restart nginx
